baseURL = 'https://neurtureapp.com/'
languageCode = 'en-us'
title = 'Neurture - Break habits with science and self-compassion'
theme = 'neurture'

[params]
  description = "Break habits with science and self-compassion with the Neurture app"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Podcast"
    url = "https://theadaptivemind.com"
    weight = 4

  # Company links
  [[menu.footer_company]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1
  [[menu.footer_company]]
    name = "Terms of Use"
    url = "/terms/"
    weight = 2
  [[menu.footer_company]]
    name = "Press Kit"
    url = "/press-kit/"
    weight = 3
  [[menu.footer_company]]
    name = "Copyright"
    url = "/copyright/"
    weight = 4
  
  # Organization links
  [[menu.footer_organizations]]
    name = "For Universities"
    url = "/universities/"
    weight = 1
  [[menu.footer_organizations]]
    name = "For Employers"
    url = "/employers/"
    weight = 2
  [[menu.footer_organizations]]
    name = "For Rehab Centers"
    url = "/rehab/"
    weight = 3
